## YAML Template.
---
dropbox:
    accesstoken: j2TjO0jzmaAAAAAAAAAADDK05zGIMCE6Ntekui5nvTMY6t-2ZvM3Xb2UNGwkCcdv
spring:
    servlet:
        multipart:
            max-file-size:  128KB
            max-request-size: 128KB
            
storageProvider: dropbox
